name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - lecture*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'

      - name: Move to lecture directory
        run: cd lecture01
      - name: assemble
        run: ./gradlew assemble
      - name: check
        run: ./gradlew check

